// <auto-generated />
using Connect4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connect4.Migrations.MsSql.Migrations
{
	[DbContext( typeof( AppDbContext ) )]
	[Migration( "20220404135539_InitialCreate" )]
	partial class InitialCreate
	{
		protected override void BuildTargetModel( ModelBuilder modelBuilder )
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation( "ProductVersion", "6.0.3" )
				.HasAnnotation( "Relational:MaxIdentifierLength", 128 );

			SqlServerModelBuilderExtensions.UseIdentityColumns( modelBuilder, 1L, 1 );
#pragma warning restore 612, 618
		}
	}
}
