// <auto-generated />
using System;
using Connect4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connect4.Migrations.MsSql.Migrations
{
	[DbContext( typeof( AppDbContext ) )]
	[Migration( "20220404140059_AddGamesTable" )]
	partial class AddGamesTable
	{
		protected override void BuildTargetModel( ModelBuilder modelBuilder )
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation( "ProductVersion", "6.0.3" )
				.HasAnnotation( "Relational:MaxIdentifierLength", 128 );

			SqlServerModelBuilderExtensions.UseIdentityColumns( modelBuilder, 1L, 1 );

			modelBuilder.Entity( "Connect4.Domain.Models.GameModel", b =>
				 {
					 b.Property<int>( "Id" )
						 .ValueGeneratedOnAdd()
						 .HasColumnType( "int" );

					 SqlServerPropertyBuilderExtensions.UseIdentityColumn( b.Property<int>( "Id" ), 1L, 1 );

					 b.Property<string>( "State" )
						 .IsRequired()
						 .HasColumnType( "nvarchar(max)" );

					 b.Property<Guid>( "Uuid" )
						 .HasColumnType( "uniqueidentifier" );

					 b.HasKey( "Id" );

					 b.HasIndex( "Uuid" );

					 b.ToTable( "Games" );
				 } );
#pragma warning restore 612, 618
		}
	}
}
