// <auto-generated />
using System;
using Connect4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connect4.Migrations.MsSql.Migrations
{
	[DbContext( typeof( AppDbContext ) )]
	[Migration( "20220414201935_UniqueGameUuidIx" )]
	partial class UniqueGameUuidIx
	{
		protected override void BuildTargetModel( ModelBuilder modelBuilder )
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation( "ProductVersion", "6.0.3" )
				.HasAnnotation( "Relational:MaxIdentifierLength", 128 );

			SqlServerModelBuilderExtensions.UseIdentityColumns( modelBuilder, 1L, 1 );

			modelBuilder.Entity( "Connect4.Domain.Models.GameModel", b =>
				 {
					 b.Property<int>( "Id" )
						 .ValueGeneratedOnAdd()
						 .HasColumnType( "int" );

					 SqlServerPropertyBuilderExtensions.UseIdentityColumn( b.Property<int>( "Id" ), 1L, 1 );

					 b.Property<int>( "CurrentPlayer" )
						 .HasColumnType( "int" );

					 b.Property<int>( "NumberPlayers" )
						 .HasColumnType( "int" );

					 b.Property<int>( "ToConnect" )
						 .HasColumnType( "int" );

					 b.Property<Guid>( "Uuid" )
						 .HasColumnType( "uniqueidentifier" );

					 b.Property<string>( "WellState" )
						 .IsRequired()
						 .HasColumnType( "nvarchar(max)" );

					 b.Property<int?>( "Winner" )
						 .HasColumnType( "int" );

					 b.HasKey( "Id" );

					 b.HasIndex( "Uuid" )
						 .IsUnique();

					 b.ToTable( "Games" );
				 } );
#pragma warning restore 612, 618
		}
	}
}
